services:
  db:
    image: postgres:16
    container_name: drivetrack_db
    environment:
      POSTGRES_USER: drivetrack
      POSTGRES_PASSWORD: password
      POSTGRES_DB: drivetrack
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
